/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhistleblowerRouteImport } from './routes/whistleblower'
import { Route as TrustCenterRouteImport } from './routes/trust-center'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitStoryRouteImport } from './routes/submit-story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FactCheckRouteImport } from './routes/fact-check'
import { Route as EditorialPolicyRouteImport } from './routes/editorial-policy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorrectionsRouteImport } from './routes/corrections'
import { Route as ContributorRouteImport } from './routes/contributor'
import { Route as ContributeRouteImport } from './routes/contribute'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContributorIndexRouteImport } from './routes/contributor.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PostSlugRouteImport } from './routes/post.$slug'
import { Route as ContributorWalletRouteImport } from './routes/contributor.wallet'
import { Route as ContributorSubmitRouteImport } from './routes/contributor.submit'
import { Route as ContributorSubmissionsRouteImport } from './routes/contributor.submissions'
import { Route as ContributorReferralsRouteImport } from './routes/contributor.referrals'
import { Route as ContributorPayoutsRouteImport } from './routes/contributor.payouts'
import { Route as ContributorOnboardingRouteImport } from './routes/contributor.onboarding'
import { Route as ContributorNotificationsRouteImport } from './routes/contributor.notifications'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AuthorIdRouteImport } from './routes/author.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ArticleSlugRevisionsRouteImport } from './routes/article.$slug.revisions'
import { Route as AdminEditIdRouteImport } from './routes/admin.edit.$id'

const WhistleblowerRoute = WhistleblowerRouteImport.update({
  id: '/whistleblower',
  path: '/whistleblower',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustCenterRoute = TrustCenterRouteImport.update({
  id: '/trust-center',
  path: '/trust-center',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitStoryRoute = SubmitStoryRouteImport.update({
  id: '/submit-story',
  path: '/submit-story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FactCheckRoute = FactCheckRouteImport.update({
  id: '/fact-check',
  path: '/fact-check',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorialPolicyRoute = EditorialPolicyRouteImport.update({
  id: '/editorial-policy',
  path: '/editorial-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrectionsRoute = CorrectionsRouteImport.update({
  id: '/corrections',
  path: '/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorRoute = ContributorRouteImport.update({
  id: '/contributor',
  path: '/contributor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeRoute = ContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorIndexRoute = ContributorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContributorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PostSlugRoute = PostSlugRouteImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorWalletRoute = ContributorWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorSubmitRoute = ContributorSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorSubmissionsRoute = ContributorSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorReferralsRoute = ContributorReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorPayoutsRoute = ContributorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorOnboardingRoute = ContributorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ContributorRoute,
} as any)
const ContributorNotificationsRoute =
  ContributorNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ContributorRoute,
  } as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorIdRoute = AuthorIdRouteImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ArticleSlugRevisionsRoute = ArticleSlugRevisionsRouteImport.update({
  id: '/article/$slug/revisions',
  path: '/article/$slug/revisions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditIdRoute = AdminEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/contributor': typeof ContributorRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-check': typeof FactCheckRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-story': typeof SubmitStoryRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/trust-center': typeof TrustCenterRoute
  '/whistleblower': typeof WhistleblowerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/author/$id': typeof AuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contributor/notifications': typeof ContributorNotificationsRoute
  '/contributor/onboarding': typeof ContributorOnboardingRoute
  '/contributor/payouts': typeof ContributorPayoutsRoute
  '/contributor/referrals': typeof ContributorReferralsRoute
  '/contributor/submissions': typeof ContributorSubmissionsRoute
  '/contributor/submit': typeof ContributorSubmitRoute
  '/contributor/wallet': typeof ContributorWalletRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/contributor/': typeof ContributorIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/article/$slug/revisions': typeof ArticleSlugRevisionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/corrections': typeof CorrectionsRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-check': typeof FactCheckRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-story': typeof SubmitStoryRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/trust-center': typeof TrustCenterRoute
  '/whistleblower': typeof WhistleblowerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/author/$id': typeof AuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contributor/notifications': typeof ContributorNotificationsRoute
  '/contributor/onboarding': typeof ContributorOnboardingRoute
  '/contributor/payouts': typeof ContributorPayoutsRoute
  '/contributor/referrals': typeof ContributorReferralsRoute
  '/contributor/submissions': typeof ContributorSubmissionsRoute
  '/contributor/submit': typeof ContributorSubmitRoute
  '/contributor/wallet': typeof ContributorWalletRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin': typeof AdminIndexRoute
  '/contributor': typeof ContributorIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/article/$slug/revisions': typeof ArticleSlugRevisionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/advertise': typeof AdvertiseRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contribute': typeof ContributeRoute
  '/contributor': typeof ContributorRouteWithChildren
  '/corrections': typeof CorrectionsRoute
  '/dashboard': typeof DashboardRoute
  '/editorial-policy': typeof EditorialPolicyRoute
  '/fact-check': typeof FactCheckRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/newsletter': typeof NewsletterRoute
  '/privacy': typeof PrivacyRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/submit-story': typeof SubmitStoryRoute
  '/terms': typeof TermsRoute
  '/transparency': typeof TransparencyRoute
  '/trust-center': typeof TrustCenterRoute
  '/whistleblower': typeof WhistleblowerRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/admin/users': typeof AdminUsersRoute
  '/author/$id': typeof AuthorIdRoute
  '/category/$slug': typeof CategorySlugRoute
  '/contributor/notifications': typeof ContributorNotificationsRoute
  '/contributor/onboarding': typeof ContributorOnboardingRoute
  '/contributor/payouts': typeof ContributorPayoutsRoute
  '/contributor/referrals': typeof ContributorReferralsRoute
  '/contributor/submissions': typeof ContributorSubmissionsRoute
  '/contributor/submit': typeof ContributorSubmitRoute
  '/contributor/wallet': typeof ContributorWalletRoute
  '/post/$slug': typeof PostSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/contributor/': typeof ContributorIndexRoute
  '/admin/edit/$id': typeof AdminEditIdRoute
  '/article/$slug/revisions': typeof ArticleSlugRevisionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/contribute'
    | '/contributor'
    | '/corrections'
    | '/dashboard'
    | '/editorial-policy'
    | '/fact-check'
    | '/leaderboard'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/submit-story'
    | '/terms'
    | '/transparency'
    | '/trust-center'
    | '/whistleblower'
    | '/admin/dashboard'
    | '/admin/moderation'
    | '/admin/new'
    | '/admin/payouts'
    | '/admin/submissions'
    | '/admin/users'
    | '/author/$id'
    | '/category/$slug'
    | '/contributor/notifications'
    | '/contributor/onboarding'
    | '/contributor/payouts'
    | '/contributor/referrals'
    | '/contributor/submissions'
    | '/contributor/submit'
    | '/contributor/wallet'
    | '/post/$slug'
    | '/admin/'
    | '/contributor/'
    | '/admin/edit/$id'
    | '/article/$slug/revisions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/contribute'
    | '/corrections'
    | '/dashboard'
    | '/editorial-policy'
    | '/fact-check'
    | '/leaderboard'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/submit-story'
    | '/terms'
    | '/transparency'
    | '/trust-center'
    | '/whistleblower'
    | '/admin/dashboard'
    | '/admin/moderation'
    | '/admin/new'
    | '/admin/payouts'
    | '/admin/submissions'
    | '/admin/users'
    | '/author/$id'
    | '/category/$slug'
    | '/contributor/notifications'
    | '/contributor/onboarding'
    | '/contributor/payouts'
    | '/contributor/referrals'
    | '/contributor/submissions'
    | '/contributor/submit'
    | '/contributor/wallet'
    | '/post/$slug'
    | '/admin'
    | '/contributor'
    | '/admin/edit/$id'
    | '/article/$slug/revisions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/advertise'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/contribute'
    | '/contributor'
    | '/corrections'
    | '/dashboard'
    | '/editorial-policy'
    | '/fact-check'
    | '/leaderboard'
    | '/login'
    | '/newsletter'
    | '/privacy'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/submit-story'
    | '/terms'
    | '/transparency'
    | '/trust-center'
    | '/whistleblower'
    | '/admin/dashboard'
    | '/admin/moderation'
    | '/admin/new'
    | '/admin/payouts'
    | '/admin/submissions'
    | '/admin/users'
    | '/author/$id'
    | '/category/$slug'
    | '/contributor/notifications'
    | '/contributor/onboarding'
    | '/contributor/payouts'
    | '/contributor/referrals'
    | '/contributor/submissions'
    | '/contributor/submit'
    | '/contributor/wallet'
    | '/post/$slug'
    | '/admin/'
    | '/contributor/'
    | '/admin/edit/$id'
    | '/article/$slug/revisions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdvertiseRoute: typeof AdvertiseRoute
  AuthRoute: typeof AuthRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContributeRoute: typeof ContributeRoute
  ContributorRoute: typeof ContributorRouteWithChildren
  CorrectionsRoute: typeof CorrectionsRoute
  DashboardRoute: typeof DashboardRoute
  EditorialPolicyRoute: typeof EditorialPolicyRoute
  FactCheckRoute: typeof FactCheckRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  NewsletterRoute: typeof NewsletterRoute
  PrivacyRoute: typeof PrivacyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubmitStoryRoute: typeof SubmitStoryRoute
  TermsRoute: typeof TermsRoute
  TransparencyRoute: typeof TransparencyRoute
  TrustCenterRoute: typeof TrustCenterRoute
  WhistleblowerRoute: typeof WhistleblowerRoute
  AuthorIdRoute: typeof AuthorIdRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PostSlugRoute: typeof PostSlugRoute
  ArticleSlugRevisionsRoute: typeof ArticleSlugRevisionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whistleblower': {
      id: '/whistleblower'
      path: '/whistleblower'
      fullPath: '/whistleblower'
      preLoaderRoute: typeof WhistleblowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust-center': {
      id: '/trust-center'
      path: '/trust-center'
      fullPath: '/trust-center'
      preLoaderRoute: typeof TrustCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-story': {
      id: '/submit-story'
      path: '/submit-story'
      fullPath: '/submit-story'
      preLoaderRoute: typeof SubmitStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fact-check': {
      id: '/fact-check'
      path: '/fact-check'
      fullPath: '/fact-check'
      preLoaderRoute: typeof FactCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editorial-policy': {
      id: '/editorial-policy'
      path: '/editorial-policy'
      fullPath: '/editorial-policy'
      preLoaderRoute: typeof EditorialPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corrections': {
      id: '/corrections'
      path: '/corrections'
      fullPath: '/corrections'
      preLoaderRoute: typeof CorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor': {
      id: '/contributor'
      path: '/contributor'
      fullPath: '/contributor'
      preLoaderRoute: typeof ContributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute': {
      id: '/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof ContributeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/': {
      id: '/contributor/'
      path: '/'
      fullPath: '/contributor/'
      preLoaderRoute: typeof ContributorIndexRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/post/$slug': {
      id: '/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof PostSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/wallet': {
      id: '/contributor/wallet'
      path: '/wallet'
      fullPath: '/contributor/wallet'
      preLoaderRoute: typeof ContributorWalletRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/submit': {
      id: '/contributor/submit'
      path: '/submit'
      fullPath: '/contributor/submit'
      preLoaderRoute: typeof ContributorSubmitRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/submissions': {
      id: '/contributor/submissions'
      path: '/submissions'
      fullPath: '/contributor/submissions'
      preLoaderRoute: typeof ContributorSubmissionsRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/referrals': {
      id: '/contributor/referrals'
      path: '/referrals'
      fullPath: '/contributor/referrals'
      preLoaderRoute: typeof ContributorReferralsRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/payouts': {
      id: '/contributor/payouts'
      path: '/payouts'
      fullPath: '/contributor/payouts'
      preLoaderRoute: typeof ContributorPayoutsRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/onboarding': {
      id: '/contributor/onboarding'
      path: '/onboarding'
      fullPath: '/contributor/onboarding'
      preLoaderRoute: typeof ContributorOnboardingRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/contributor/notifications': {
      id: '/contributor/notifications'
      path: '/notifications'
      fullPath: '/contributor/notifications'
      preLoaderRoute: typeof ContributorNotificationsRouteImport
      parentRoute: typeof ContributorRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author/$id': {
      id: '/author/$id'
      path: '/author/$id'
      fullPath: '/author/$id'
      preLoaderRoute: typeof AuthorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/article/$slug/revisions': {
      id: '/article/$slug/revisions'
      path: '/article/$slug/revisions'
      fullPath: '/article/$slug/revisions'
      preLoaderRoute: typeof ArticleSlugRevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/edit/$id': {
      id: '/admin/edit/$id'
      path: '/edit/$id'
      fullPath: '/admin/edit/$id'
      preLoaderRoute: typeof AdminEditIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminNewRoute: typeof AdminNewRoute
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditIdRoute: typeof AdminEditIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminNewRoute: AdminNewRoute,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditIdRoute: AdminEditIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ContributorRouteChildren {
  ContributorNotificationsRoute: typeof ContributorNotificationsRoute
  ContributorOnboardingRoute: typeof ContributorOnboardingRoute
  ContributorPayoutsRoute: typeof ContributorPayoutsRoute
  ContributorReferralsRoute: typeof ContributorReferralsRoute
  ContributorSubmissionsRoute: typeof ContributorSubmissionsRoute
  ContributorSubmitRoute: typeof ContributorSubmitRoute
  ContributorWalletRoute: typeof ContributorWalletRoute
  ContributorIndexRoute: typeof ContributorIndexRoute
}

const ContributorRouteChildren: ContributorRouteChildren = {
  ContributorNotificationsRoute: ContributorNotificationsRoute,
  ContributorOnboardingRoute: ContributorOnboardingRoute,
  ContributorPayoutsRoute: ContributorPayoutsRoute,
  ContributorReferralsRoute: ContributorReferralsRoute,
  ContributorSubmissionsRoute: ContributorSubmissionsRoute,
  ContributorSubmitRoute: ContributorSubmitRoute,
  ContributorWalletRoute: ContributorWalletRoute,
  ContributorIndexRoute: ContributorIndexRoute,
}

const ContributorRouteWithChildren = ContributorRoute._addFileChildren(
  ContributorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdvertiseRoute: AdvertiseRoute,
  AuthRoute: AuthRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContributeRoute: ContributeRoute,
  ContributorRoute: ContributorRouteWithChildren,
  CorrectionsRoute: CorrectionsRoute,
  DashboardRoute: DashboardRoute,
  EditorialPolicyRoute: EditorialPolicyRoute,
  FactCheckRoute: FactCheckRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  NewsletterRoute: NewsletterRoute,
  PrivacyRoute: PrivacyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubmitStoryRoute: SubmitStoryRoute,
  TermsRoute: TermsRoute,
  TransparencyRoute: TransparencyRoute,
  TrustCenterRoute: TrustCenterRoute,
  WhistleblowerRoute: WhistleblowerRoute,
  AuthorIdRoute: AuthorIdRoute,
  CategorySlugRoute: CategorySlugRoute,
  PostSlugRoute: PostSlugRoute,
  ArticleSlugRevisionsRoute: ArticleSlugRevisionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
